### ISSUE TITLE
Error occurred at the OAuth process

### ISSUE THREAD

**Issue by Ruriko** [mixmoe/HibiAPI#232]
I get this error when I view pixiv api
`{"error":{"user_message":"","message":"Error occurred at the OAuth process. Please check your Access Token to fix this. Error Message: invalid_grant","reason":"","user_message_details":{}}}`
To fix this error I just reboot the server and it works again. I want to avoid rebooting all the time so how can I fix this?

here the error log: https://pastebin.com/raw/cPQjgtij
I can't paste log here due to maximum character limit

**Comment by mnixry** [comment]
It looks weird, because an error like this has never happened on the Public Demo.

Problems may be caused by the account identity refresh, I've noticed there are some logs like this:

```
2022-02-22 11:57:15.707 | INFO     | hibiapi.app.routes.pixiv:refresh_identity:41 - Trying to refresh Pixiv account identity.
2022-02-22 11:57:15.708 | INFO     | hibiapi.app.routes.pixiv:refresh_identity:47 - Successfully logged in Pixiv account as SweetCosplay(user_htje2345).
```

Is this problem still exists after these log shown? (If you enabled cache, it may cache the failed result, try to refresh it if possible)

---

I have a question that may be offensive, I'm particularly curious about your use of this API, and why you haven't used Chinese to raise issues, even though it's a Chinese repository?

**Comment by Ruriko** [comment]
Never mind I found the problem I had cloudflare enabled. 
I use the API to make a pixiv mirror site. I don't know chinese so I speak in english. I just use google translate to translate the wiki

**Comment by mnixry** [comment]
I tried to optimize the refresh of the Pixiv login credential, you can try again.
